services:
    marttiphpbb.grouptempvars.listener:
        class: marttiphpbb\grouptempvars\event\listener
        arguments:
            - '@dbal.conn'
            - '@user'
            - '%tables.user_group%'
        tags:
            - { name: event.listener }
