parameters:
    dmzx.mchat.table.mchat: %core.table_prefix%mchat
    dmzx.mchat.table.mchat_deleted_messages: %core.table_prefix%mchat_deleted_messages
    dmzx.mchat.table.mchat_sessions: %core.table_prefix%mchat_sessions
